### ISSUE TITLE
Remove postheader_posttitle "Permalink to" text from .entry-title

### ISSUE THREAD

**Issue by scottnix** [ThematicTheme/Thematic#102]
Currently on the `thematic_postheader_posttitle` there is a title added which appends the text "Permalink to <blog title>. This drives the SEO in me crazy, but recently I haven't been a fan of adding the title at all since it generates exactly the same as it will render in plain text, which makes it unneeded. The title (when hovered over) will also produce a tooltip with the same text.

Maybe I am missing a use case in where this would be beneficial, but currently the Twenty Thirteen & Fourteen themes also do not apply titles.

While it would be nice to drop the title attribute completely, at least removing the "Permalink to" from it would be nice. :)

**Comment by falcoraptor** [comment]
I did a little research and it seems the practice of the title attributes just followed along from a long time ago and has no clear benefit.
https://core.trac.wordpress.org/ticket/24203

I think we can safely remove the title attribute completely.

**Comment by scottnix** [comment]
I will double check Thematic, I think there is one more section that uses "Permalink to" which may fall into the same category of legacy stuff done for no purpose. :P

**Comment by falcoraptor** [comment]
I found two more places. There are permalink title attributes on featured thumbnails and on custom post type archive links. 
Are these also candidates for removal?
Although the title in this case differ from the content of the link?

**Comment by ghost** [comment]
looking at 2.0 as a last chance for making major changes in output i say Scotts got a point with abandoning the old practice

**Comment by falcoraptor** [comment]
I've removed a bunch of title attributes throughout. The use - or rather reliance on it - is generally discouraged in html5 since it excludes keyboard-only users as well as touch-only users. It's basically useless for tablets and mobile.
References
http://mrwweb.com/the-title-attribute-and-why-its-almost-useless/
http://www.paciellogroup.com/blog/2013/01/using-the-html-title-attribute-updated/

This is a good start in an accessibility effort. I'd like the next release to get Thematic as far as possible in this regard and earn the accessibility-ready tag in the theme repo.

This also removes some strings for translation. It's not a huge deal. I will regenerate a pot file before release but having unused strings in the translation files is much less serious than having strings untranslated.
