### ISSUE TITLE
Any news for 2.0?

### ISSUE THREAD

**Issue by joeharby** [ThematicTheme/Thematic#107]
Did 2.0 get released on January 30th or has the release date changed?

**Comment by falcoraptor** [comment]
Unfortunately it didn't :( 

And I haven't set a new release date either because I am still waiting for feedback from the other developer. But the develop branch is feature complete and basically ready to go. There's just some last polishing left to to in prepping it for release. See the issues https://github.com/ThematicTheme/Thematic/issues?direction=desc&milestone=2&page=1&sort=updated&state=open

I have no control over when it can appear in the wordpress.org repo, but I am willing to clean the last things up, tag it 2.0 beta and tell people to have a go with it. While I of course have run tests on it, the more people that get their hands on it and report any issues, the more stable it has a chance to get. If you are interested, the zip download link is https://github.com/ThematicTheme/Thematic/archive/develop.zip That will fetch the latest state of the development version.

Unfortunately there are some problem with the thematictheme site and some people have been locked out, including me. So I can't post there with an announcement, but I'll make it ready anyway.

**Comment by scottnix** [comment]
I am not locked out, I got locked out a long time ago and I think Gene put me on a white list, so if you have any news/announcements you want to post there, just send me an email and I can throw it up.

Any thoughts on possibly opening a section on Github either under the ThematicTheme umbrella, or on your personal Github section to allow a ThematicForum repository section where people can open issues and treat it as a forum until things get fixed?

**Comment by falcoraptor** [comment]
Thanks Scott!

I'll wrap this thing up and shoot you an email when it's ready so you can post an announcement about 2.0 beta. I'm writing up some documentation too at the moment. If I don't get my access back before 2.0 beta, I'll probably publish some articles on my own site to help people out.

**Comment by falcoraptor** [comment]
@joeharby We are aiming to release the stable Thematic 2.0 soon after WordPress 4.0 is out, which means end of August/beginning of September. 

The problem with the site and forums have been dealt with and they are up and running again. 
Thank you for your patience!
