### ISSUE TITLE
missing ; in entities in german translation

### ISSUE THREAD

**Issue by Adan0s** [ThematicTheme/Thematic#19]
Hi there,

in library/languages/de_DE.po there are following two bugs:

> Line 186: `msgstr "<span class=\"meta-nav\">&laquo;</span> &Auml;ltere Beitr&aumlge"`
> needs to be 
> Line 186: `msgstr "<span class=\"meta-nav\">&laquo;</span> &Auml;ltere Beitr&auml;ge"`

and

> Line 191: `msgstr "Neuere Beitr&aumlge <span class=\"meta-nav\">&raquo;</span>"`
> needs to be
> Line 191: `msgstr "Neuere Beitr&auml;ge <span class=\"meta-nav\">&raquo;</span>"`

**Comment by helgatheviking** [comment]
the 1.0.3 release radically overhauled all the text strings.  if you are interested, you should check out:
http://translate.thematictheme.com/projects/thematic-framework/thematic-103/de/default

that's the site being used to make it easier to contribute translations

if you can do that today or tomorrow it will be included in the 1.0.3 release

**Comment by Adan0s** [comment]
Thank you. I already wrote a comment in the news at the site but I'll ask here again just to make sure: Should we include HTML-Entities for umlauts?

**Comment by helgatheviking** [comment]
unfortunately no one really checks those comments w/ any frequency.  @middlesister might have an answer about non-standard characters.  as a native english speaker i haven't the faintest clue.

**Comment by falcoraptor** [comment]
I am actually not sure myself. In my first translation of Thematic I did not use HTML-entities because I figured support of utf-8 ought to be widespread enough these days. I later changed to use them because of another forum member who thought it would be best as a safety precaution.

I would love to be able to ditch them, it makes things soo much easier to read.

**Comment by falcoraptor** [comment]
@Adan0s I'm in the process of adding the translations from glotpress into the repo. I see you have added corrections to some strings in german, but they are still in waiting status. @ChrisGossmann  is a validator for german but I haven't heard from him in a while. Would you like to be a validator for german too? I can promote you so you can mark the strings as correct. They won't make it for the 1.0.3 release but for the future.

**Comment by ghost** [comment]
Adan0s Thanks for all your help. I have added you as a validator for the German Locale. This enables you to edit the status of the strings from "waiting" to "approved" or "rejected". This is assuming that your username over there begins with "martin" If not let me know your user name so that I can add you. Your help is much appreciated! Thanks again!
