### ISSUE TITLE
get_permalink doesn’t return full permalinks

### ISSUE THREAD

**Issue by ElectroLund** [ThematicTheme/Thematic#22]
This bug can be seen with the built-in WP recent comment widget.   Even with comment pagination turned off, permalinks look like this: 

http://yoursite.com/archive-path/post-name/comment-page-1/

Should have a bookmark in the HTML at the end like this: "#post-1745”

See forums for background:
http://thematictheme.com/forums/topic/recent-comment-widget-problem/

**Comment by falcoraptor** [comment]
It's easy enough to tack on the last #comment-ID bit, that was just an oversight. But I need to also make sure no comment-page is added to the permalink if you are not breaking the comments into pages.

Thanks for reporting.

**Comment by falcoraptor** [comment]
Ok, I think I fixed it. 
Please test the latest version from the master branch, either by pulling/cloning with git or use the [master zipball download](https://github.com/ThematicTheme/Thematic/zipball/master)

**Comment by ElectroLund** [comment]
Wow, awesome response time!

**Comment by ElectroLund** [comment]
So it seems to be working now, although now the comment form compatibility with Jetpack seems to be broken:

define('THEMATIC_COMPATIBLE_COMMENT_FORM', true);

**Comment by helgatheviking** [comment]
all those constants were deprecated.

**Comment by ElectroLund** [comment]
How then can we use the Jetpack comment form?

**Comment by falcoraptor** [comment]
What is broken and in what way?

Using that constant made thematic render a completely own comment form. Without that constant thematic is calling the wordpress `comment_form()` function with arguments, which means it's using core functionality instead of rolling its own. I would be surprised if the core functionality would clash with jetpack. 

If you want to change the comment form you can use the filter `thematic_comment_form_args`. And if you _really_ really need the old form, you can put `add_theme_support( 'thematic_legacy_comment_form' );` in your functions.php but I would say that's the last resort. It's not been removed, just deprecated. 

Since this issue is closed maybe this question should be moved to the forums.
