### ISSUE TITLE
Dynamic classes: post class is-full

### ISSUE THREAD

**Issue by ghost** [ThematicTheme/Thematic#29]
The post class "is-full" is not properly displayed on single post views that have excerpts or more tags

**Comment by Gosha** [comment]
It might be just my child-theme. But I extensively use `.is-full` and `.is-excerpt` to differentiate my posts.
**Used to be**: Those that actually are shown as excerpts are `.is-excerpt`
**Now**: Those that have excerpts, but currently shown as full are still `.is-excerpt`
**Since**: [this commit](https://github.com/ThematicTheme/Thematic/commit/ef842105c11e1fa2c0fcc2073f9ce761ea14f0e1#L0L467)

**Comment by ghost** [comment]
Addressed in this [commit](https://github.com/ThematicTheme/Thematic/commit/5e8a7fabddf8452920b80dabe7a414c9909323d2)

**Comment by ghost** [comment]
CLosing feel free to comment if there are still issues with this latest commit.
