### ISSUE TITLE
et.po / mo from Glotpress to git?

### ISSUE THREAD

**Issue by petskratt** [ThematicTheme/Thematic#31]
What is the recommended procedure for getting latest translation from Glotpress to repo - should I export it myself and create pull request... or is it done automatically at some point?

(fixed an earlier typo, actually some months ago already...)

**Comment by falcoraptor** [comment]
It's a manual process, and therefore something we will do as part of preparing a release. If you use the latest development version from github in your work and would like to have the estonian translation in the repo, I can export it and commit it for you. Otherwise we will generally wait until the last moment before release in order to give translators as much time as possible.
