### ISSUE TITLE
Support - New Version

### ISSUE THREAD

**Issue by joesnellpdx** [ThematicTheme/Thematic#34]
Totally love Thematic, but is it still being supported?

Other than the fact that it is 'open source' it seems to need a little refresh.

Mainly, it could use a little HTML5'ing (a la HTML5 Boilerplate) plus usage of classes instead of id's in the syntax & css.

I keep thinking of morphing it myself, but feel like an update may be out 'at any moment!' ... 

Am I holding my breath for nothing?

Thanks!

**Comment by ghost** [comment]
Hi Joseph,

Yes it's still being supported. thematictheme.com/forums And yes, it's still being developed. version 1.0.4 is about to hit wp dot org/extend at as soon as a human syncs from trac.

Thematic will see a doctype change but the hurdle that has to be overcome is backward compatibility. Thematic's intended use as a parent theme puts added responsibilities on it. The tags and attributes can't suddenly change the way it can in a starter theme like _s. It has to support existing installations of Thematic with an upgradable path otherwise changing markup may break sites and affect SEO. 

Middlesister and I are currently ( moments ago ) discussing how to provide a legacy feature frozen mode and move the doctype onward to html5. 

Thoughts, suggestions, pull requests are always welcome. Stay tuned and don't let this conversation drop. I hope to hear more from you.

**Comment by joesnellpdx** [comment]
Thanks for the info and the quick reply! I understand the complexities for sure. The flip side are all the functions folks are running to 're-write' the theme to HTML5, etc, etc. 

Looking forward to 1.0.4 and news on other updates for sure!

Joe

**Comment by falcoraptor** [comment]
If you haven't seen it, I wrote a plugin that will switch the markup to html5. You can download it from the wordpress repository at http://wordpress.org/extend/plugins/thematic-html5/
 But yes, the trick is to make upgrading smooth. We need backwards compatibility for old installations that are not about to switch doctype just yet, and consider newer installs where the child themes have been wrangling their own functions for html5. But hopefully the latter are still maintained and those functions could just be deleted when the parent theme gets updated.

**Comment by joesnellpdx** [comment]
Rockin. Thanks the the tip on the plugin. That's handy for sure. I've used a child theme that has been already html5ified & uses classes instead of id's ... would be nice to not have to 'undo,' however...

If I had a vote, I'd put my hand up for Thematic 2 - start anew.

**Comment by ghost** [comment]
Please take a look at the develop branch for a preview of a proposed compatibility/leagcy mode as we move forward .
Code comments are very welcome.

**Comment by falcoraptor** [comment]
I'm closing this as part of issue cleanup.
