### ISSUE TITLE
Remove Depreciated Blog and Depreciated Archives Templates

### ISSUE THREAD

**Issue by JamesGeiger** [ThematicTheme/Thematic#38]
@middlesister I think it is time they be put to rest. By the time 1.1 rolls out its safe to say enough time has elapsed to justify removing them, no?

Templates in question: archive.php and template-page-blog.php

**Comment by falcoraptor** [comment]
Yes I agree. I don't know how long they have been deprecated, and I don't know how long one has to keep things around. But if we are doing a clean break I am all for getting rid of them.

I'd like to hear Gene's opinion on it. This is not like functions where we can throw deprecated warnings or errors. If the files are gone, they are gone. But having them there means they show up in admin and people can use them - even though they are deprecated.

**Comment by JamesGeiger** [comment]
@middlesister you know what the Links page is irrelevant now since there is no Links section in the admin anymore, right?

**Comment by falcoraptor** [comment]
Haha yes that is true.

**Comment by ghost** [comment]
We can remove the templates that have already been deprecated in the develop branch. There has been plenty of time for people to realize that they are going away.

The links template I'm not so sure about... Just because something has been removed from core does not mean that it has been removed from use altogether. 

See: http://wordpress.org/plugins/link-manager/ 

Given the age of Thematic, I think that removing that deprecating and removing that template is a bad idea. It will break sites for people that have used this template and could have possibly installed the Link Manager plugin to keep that functionality in the admin.

**Comment by JamesGeiger** [comment]
@emhr Let's just deprecate the Links page then.
