### ISSUE TITLE
Append child theme name instead of thematic_style

### ISSUE THREAD

**Issue by JamesGeiger** [ThematicTheme/Thematic#39]
Instead of id='thematic_style-css' it should be id='childthemename-style-css'

See https://github.com/justintadlock/hybrid-core/blob/master/functions/utility.php#L109 for how it's done

**Comment by falcoraptor** [comment]
What is it that you are referring to here? Is it the name of the enqueued stylesheet?

Why would you want to change that to use the child theme name? The name comes from the handle used in `wp_enqueque_scripts`. The way it is now, if a child theme wants to remove the default styles completely it can  dequeue the styleseheet using the handle `thematic_style`. 

I think it would be confusing if they were to dequeue the parent stylesheet using a handle named `childthemename-style`. And then if a child theme tries to enqueue a stylesheet with the handle `childthemename-style`, it would not get used since the name would already be taken. So I am skeptic to the idea.

**Comment by falcoraptor** [comment]
Ok I see where you are getting at. I activated the sample child theme and saw that the _child_ stylesheet is enqueued with the handle of `thematic_style`. So you are right, it should be changed to `childthemename-style`. If we chose to go the same route regarding styles as we do now, as per the discussion started at #41

**Comment by JamesGeiger** [comment]
@middlesister see I am always right ;) haha jk

**Comment by falcoraptor** [comment]
:) 
This is the simple fix for the issue while the rest is waiting to be decided
