### ISSUE TITLE
Rename blog-title and blog-description to use site instead of blog

### ISSUE THREAD

**Issue by JamesGeiger** [ThematicTheme/Thematic#47]
Is this possible or will older sites get borked?

**Comment by scottnix** [comment]
Changing a class would cause a bunch of styling issues on sites.

However for reference (since I looked and others may be curious), in the WordPress Admin, the Visual Theme Customizer and General Settings use "Site Title" and "Tagline". It would make sense to switch to something closer to those naming conventions though.

**Comment by falcoraptor** [comment]
Closing this and moving discussion to #50
