### ISSUE TITLE
Monster Widget Produces Error Messages When Used in Some Widget Areas 

### ISSUE THREAD

**Issue by Cais** [ThematicTheme/Thematic#75]
First noticed in the "footer" widget areas, feel free to just drop the Monster Widget in one and you will see a few notices as you scroll down the output.

It appears to be related to the code found here: \library\extensions\widgets-extensions.php:281

Specifically with these lines:
// Remove WP default Widgets
 // WP 2.8 function using $widget_class
    unregister_widget( 'WP_Widget_Meta' );
    unregister_widget( 'WP_Widget_Search' );

 // Finished intializing Widgets plugin, now let's load the thematic default widgets
 register_widget( 'Thematic_Widget_Search' );
 register_widget( 'Thematic_Widget_Meta' );

Commenting out each of those unregister / register lines will remove the error messages but I have not delved further into the code to address that modifications deeper effects.

**Comment by falcoraptor** [comment]
Thank you for reporting.

I also noticed while testing against 3.8 some errors in the Theme Customizer Preview related to Thematic auto-registering widgets in the sidebar, so I already had checking the widgets code on my todo-list.

We are currently doing a big revamp with updating to html5 markup and responsive styles. I am prepared to deprecate some of this functionality if needed and move on. Some things in Thematic are leftovers from a time when they were improvements, but where today things are done better in core or really belongs in a plugin. 

It is obvious that the widget-extensions.php needs some attention, there's probably a bunch of old code in there that needs cleanup. Thanks again for testing out!

**Comment by Cais** [comment]
Thanks for the follow-up, Karin!

You wouldn't happen to have a road-map where this will be taken care of?

Edward Caissie
aka Cais.

**Comment by falcoraptor** [comment]
Hm, well my goal was to have the 2.0 update finished around the same time as 3.8 rolled out, but that's obviously not happened :)

The html5 is mostly there, the responsive styling has a draft but is rough and need polishing plus a run through the latest Theme Unit Test data. And then there is testing the transition for child themes so as little as possible is breaking. 

I can make the widgets a priority for next week so that a fix can get into the develop branch as soon as possible. Hopefully the 2.0 can be submitted to .org if not before the end of the year then at least in January.

**Comment by Cais** [comment]
Thanks, Karin!

I really appreciate the overview and can definitely understand the schedule
given the time of year and the undertaking you have planned.

Good work and best of successes with the updates!

Edward Caissie
aka Cais.

**Comment by falcoraptor** [comment]
I had a quick look and this error seems to be because Thematic is replacing WP_Widget_Meta and WP_Widget_Search with its own (prefixed) version, they are now unregistered and when monster widget tries to add them they no longer exist. Thus the undefined index error. 

I am aware of the discussion around replacing core widgets and I will re-check if it is really necessary. But I believe this error is specific to the testing setup of the monster widget and won't affect regular users.

**Comment by Cais** [comment]
Thanks, again, for looking further into this. I found much the same thing ... I was not really able to reproduce it with other widgets but Monster Widget is a common tool used for theme reviews and as such I tend to go with its results as it basically creates issues that should be considered.

I found a quick work-around to re-add the core widgets and "unregister" the Thematic replacements at a later priority. The messages are cleared and I am not seeing anything affected elsewhere ... yet.

**Comment by Cais** [comment]
Oops ... jittery mouse finger (_grin_)

**Comment by falcoraptor** [comment]
:)

I thought I could check if monster widget was present and only re-register the widgets if its not. The annoying thing is `is_active_widget()` is not available at `widgets_init`. 

One workaround could be to check `if( !isset( $wp_widget_factory->widgets['Monster_Widget'] ) )` and only re-register the widgets if no Monster widget is found. The drawback is that then the widgets wouldn't be re-registered, i.e. not show up at all, merely by the Monster widget plugin being active - _regardless of whether a monster widget have been added to a widget area or not_. 

It feels a little bit sneaky to me, since I think the likelihood of a theme reviewer having monster widget in the test install is pretty big. And then the reviewer would have no chance of seeing this unless digging through the code, which I don't think is neither fair nor too likely considering the complexity of the theme.

An alternative is to create a new function hooked to `init` and check `is_active_widget()` and do the un-/re-registering there. What do you say?

**Comment by Cais** [comment]
I'm not certain any work-around that hides a common testing tool's output should even be considered. If it is an issue with how the Monster Widget is coded, then I imagine Mike and the other Theme Wranglers would want to address it correctly; but if it falls only to how Thematic is coded (as this issue does not appear elsewhere) then a solution should be sorted out versus a work-around for the Monster Widget.

If this was a widget designed for everyday use, I might see a work-around as a potential solution and the theme's limitation documented in that regard, but the crux of the matter seems to be falling to the unregistered core widgets, can they simply not be unregistered? Or, can the theme specific widgets be moved into a plugin that enhances Thematic when that plugin is activated? Just some thoughts ... (slightly tempered by my Theme Review Team admin hat).

**Comment by falcoraptor** [comment]
Well I agree with you there. It's better to question if unregistering the widgets are necessary at all. To be honest, I wasn't really aware that Thematic was unregistering core widgets. Thematic has a long history and even I don't know everything inside out. We are working to get it more up to date and in line with current best practices, one step at a time. So thank you for bringing this to my attention.

The Search widget is only applying a `<label>` tag around the widget title and making sure the title is never empty. I think that whole functionality could be replaced with a `widget_title` filter instead.

The Meta widget is basically a split up with only the login/logout links in Meta and then a separate RSS_Links widget for the RSS links. I don't see why we couldn't just rename it "Thematic Meta" or "Login/Logout links" and have both alongside the core widgets.

I'm not sure the difference in functionality is big enough to warrant putting in a plugin. The modifications seem pretty small to me. I was not involved when they were added so I don't know the reasoning behind them. I'll ask what @emhr has to say, he has been on the project longer than I and can maybe shed some light there.
