### ISSUE TITLE
Child theme does not work properly after updating Thematic parent

### ISSUE THREAD

**Issue by vita444** [ThematicTheme/Thematic#86]
In 2010 I created my Thematic child theme based on Thematic 0.9.6.2. During the years I updated from WP 2.9.2 to the current 3.8. Although not remembering I obviously updated the Thematic parent theme up to version 1.0.3.2, too, as I can see in my latest backup of the css-file. So far everything worked properly.

After updating to WP 3.8 "Parker" now I was suggested to update my Thematic parent theme as well, because I "seemed to run a child theme". So I did. Right after the updates still everything seemed to work properly. But one day later my horizontal menu did not work any more!

In my child theme I included some scripts in the horizontal menu. So hovering over the main menu items opens the submenu of the secondary pages below. Hovering over the secondary pages opens the menu of their child pages. Additionally the currently hovered item changes the color, so you always know, which page your click will open.

The occuring problems: After the update(s) none of the scripts seem to work any more.

a) Hovering over the main menu items still effects a color change of the currently hovered item. But after leaving the item the color does not switch back to the primary color or it takes a lot of time. So after hovering over all items of the usually black backgrounded horizontal menu the whole menu is light grey in the end. :-(

b) Much more important and really bad for my business: The sub menus are not shown any more! So it is impossible to read the child pages below the main items. Therefore visitors and potential customers miss a lot of important information about my company. (I did not link to the child pages on every page, because to keep them updated would cause a lot of effort. Therefore I have a custom menu with all pages and subpages, which is updated. This one is still shown. But I am not sure, if every visitor will notice it.)

Announcement, if neccessary: I am not sure, if this function belongs to Thematic itself or to my child, but hovering links in the text causes a change of the link background. This still works.

My questions:

Actually I am not sure, if the parent theme update, the WP update oder even something at my provider does cause the trouble. Most probably the theme does not work with WP 3.8. Bit I am kinda confused, because right after updating it seem to work. So be so kind togive me some ffeedback, what I can do n the meanwhile. 

Thanx in advance!
Vita

**Comment by JamesGeiger** [comment]
@vita444 First, disable all plugins and see if that does anything. Second, please create a pastebin with your function so I can take a look. Also, do you have a live link to your site?

**Comment by vita444** [comment]
@SeamlessThemes Thanx for your fast reply. I thought of broken scripts and disabled them in the meanwhile. It worked so far that the submenus were shown again. But the width was limited, so the titles of the subpages were cut. 

I tried your advice and disabled and enabled all plugins again. It seems the mistake was related to the plugin "pb-embedFlash". After disabling this one everything seems to work properly now. So my question seems to be solved.

Nevertheless if it helps to fix something else, I still can create a pastebin. Because I am no developer, but just a private user I would need some advice for that and more detail which function would be needed. Should I create one and link to my site?

**Comment by JamesGeiger** [comment]
Yes, why not...it won't hurt to have me take a look :)

**Comment by vita444** [comment]
:-D Hopefully not! ;-) 

So, how can I create a pastebin and which function did you mean?

**Comment by JamesGeiger** [comment]
Well, you can just paste your whole functions.php into http://pastebin.com/ and then save it and then link it here.

**Comment by vita444** [comment]
Ok, let's see, if it works. :-) 

http://pastebin.com/BFuXP8pP

This is the function.php of the child theme. As far as I rememberI did not change it.

**Comment by JamesGeiger** [comment]
It looks fine, but there seems to be a lot of legacy code in there...I am not sure if its needed.

**Comment by falcoraptor** [comment]
I was going to refer your question to the support forums, but I see you also posted there. These things are best handled in the forums, since then others can see and benefit from solving shared problems. Github is not the place for support.

That said, I am glad that you found a solution to your issue. I suggest you move any further discussion to the forums instead.

**Comment by vita444** [comment]
Hi middlesister, I am happy to have found a solution, too. :-) At first I was not sure if it is a theme problem or one caused by Wordpress itself. Because I am no developer, but assumed it to be neccessary to know it for bugfixing in further releases I  posted it here as detailed as possible to make it easier to fix the bug. (Thanks again to SeamlessThemes for his detailed help! I learned a lot during this thread for beeing able to help myself in futre in a better way, thanks. :-) ) Sorry if I caused any inconvinience or "stole" any time.

As you said for getting support for the solution I opened a post in the forum, too. But not a single person did even react. :-( Thanks God, someone in a non-theme-related forum could help me. I posted the solution and closed the thread in the forum as resolved. 

Just for my information and to make sure to post the right issue at the right place in future - whatfor are the forums and whatfor Github exactly? I thought, Github is for bugfixing by theme producers and forums for user's problems? Did I misunderstand that? (Usually I create marketing strategies, so software developing is a new world for me and I do not speak the language correctly or know all countries yet . ;-) Sorry for maybe asking "dumb" questions. )

**Comment by falcoraptor** [comment]
Yes I saw you did not get an answer in the forums very quickly. It's a bit unfortunate since everything is done by volunteers and the response time on the forums can be a bit long sometimes. The old forums used to be very active but not everybody followed in the move to the old domain. Plus I do not get email notifications on new threads in the forums, but I do get notifications on activity in github. 

My time has been focused on getting the new release ready so I have not been able to monitor the forums very well. If not others step in, I am sorry that the delay in getting answers can get long. All I can hope for is for users patience.

Yes github is for reporting bugs and forums is for troubleshooting. The thing is, your question suspected a bug but didn't know it. It was more a troubleshooting question than a bug report. A bug report can look like:

```
When I do [some action], [something] happens. I expect [something else] to happen instead.
To reproduce the error do this:
     bla, bla, bla
My Thematic version is x.x and I am running WordPress x.x
```

Something "not working properly" is not exactly a bug report but more a call for help. In the forums, we can help track down the cause of the problem, and if it turns out to be a bug in Thematic **then** create an issue in github when we know exactly what the problem is. The issue list is like a todo list for continuing development. A "I have a problem but I don't know if it's WordPress, Thematic or my service provider" is not exactly a todo item. :)

Do not be sorry for anything. I understand things can be confusing sometimes, especially for a newcomer. You needed help and you got it. All is well.
